version: "3.3"

services:
  traccar:
    image: gpproton/traccar:latest
    volumes:
      - ./logs:/opt/traccar/logs:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file: .env.sample
    command: java -Xms2048m -Xmx4096m -Djava.net.preferIPv4Stack=true -jar /opt/traccar/tracker-server.jar /opt/traccar/conf/traccar.xml
    ulimits:
      rtprio: 95
      memlock: -1
      nproc: 1024000
      nofile:
        soft: 1024000
        hard: 1024000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/"]
      interval: 35s
      timeout: 5s
      retries: 3
    ports:
      - "5001-5235:5001-5235"
      - "5001-5235:5001-5235/udp"
