version: "3.3"

services:
  traccar:
    image: gpproton/traccar:4.13
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./logs:/opt/traccar/logs:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    env_file: .env.sample
    command: java -Xms512m -Xmx4096m -Djava.net.preferIPv4Stack=true -jar /opt/traccar/tracker-server.jar /opt/traccar/conf/traccar.xml
    ulimits:
      rtprio: 95
      memlock: -1
      nproc: 1024000
      nofile:
        soft: 1024000
        hard: 1024000
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8082/"]
      interval: 35s
      timeout: 5s
      retries: 3
    ports:
      - "28082:8082"
      ## GPS103
      - "25001:5001"
      - "25001:5001/udp"
      ## TK103
      - "25002:5002"
      ## H02
      - "25013:5013"
      ## Concox
      - "25023:5023"
      ## OSMAND
      - "25055:5055"
